import { type FormEvent, useState } from "react";

import { weatherGptApi } from "../api/weatherGpt";
import { AlertCard, RecommendationCard } from "../components/dataCards";
import { Card, EmptyState, ErrorState, LoadingState } from "../components/ui";
import { useResource } from "../hooks/useResource";

const featureConfig = {
  crops: { title: "My crops", description: "Your active crops and growth stages.", load: weatherGptApi.getCrops },
  weather: { title: "Weather", description: "Current conditions, rainfall, and forecast for your farm.", load: weatherGptApi.getWeather },
  profile: { title: "Profile & settings", description: "Language and account preferences.", load: weatherGptApi.getProfile }
};

export function ResourcePage({ resource }: { resource: keyof typeof featureConfig }) {
  const config = featureConfig[resource];
  const state = useResource(config.load);
  return <div className="page"><header className="page-header"><div><p className="eyebrow">WeatherGPT</p><h1>{config.title}</h1><p>{config.description}</p></div></header><Card>{state.loading && <LoadingState />}{state.error && <ErrorState message={state.error} retry={state.refresh} />}{!state.loading && !state.error && <EmptyState title={`No ${config.title.toLowerCase()} data yet`} description="This information will appear here when the matching backend API is available." />}</Card></div>;
}

export function RecommendationsPage() {
  const state = useResource(weatherGptApi.getRecommendations);
  return <div className="page"><header className="page-header"><div><p className="eyebrow">Decision support</p><h1>Agricultural recommendations</h1><p>Recommendations are generated by the backend decision engine with supporting evidence.</p></div></header><Card>{state.loading && <LoadingState />}{state.error && <ErrorState message={state.error} retry={state.refresh} />}{!state.loading && !state.error && Array.isArray(state.data) && state.data.length > 0 ? <div className="stack">{state.data.map((item) => <RecommendationCard key={item.id} recommendation={item} />)}</div> : !state.loading && !state.error && <EmptyState title="No recommendations yet" description="Recommendations will be shown here once farm, crop, and weather data are available." />}</Card></div>;
}

export function AlertsPage() {
  const state = useResource(weatherGptApi.getAlerts);
  return <div className="page"><header className="page-header"><div><p className="eyebrow">Safety first</p><h1>Weather alerts</h1><p>Important weather risks for your farm will appear here.</p></div></header><Card>{state.loading && <LoadingState />}{state.error && <ErrorState message={state.error} retry={state.refresh} />}{!state.loading && !state.error && Array.isArray(state.data) && state.data.length > 0 ? <div className="stack">{state.data.map((item) => <AlertCard key={item.id} alert={item} />)}</div> : !state.loading && !state.error && <EmptyState title="No active alerts" description="You will see weather alerts here when alert rules are configured." />}</Card></div>;
}

export function AuthPage({ mode }: { mode: "login" | "register" }) {
  const [error, setError] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);
  const isRegister = mode === "register";
  const submit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setSubmitting(true); setError(null);
    const form = new FormData(event.currentTarget);
    try {
      const response = isRegister
        ? await weatherGptApi.register({ display_name: String(form.get("name")), email: String(form.get("email")), password: String(form.get("password")) })
        : await weatherGptApi.login({ email: String(form.get("email")), password: String(form.get("password")) });
      localStorage.setItem("weathergpt_access_token", response.access_token);
      window.location.href = "/dashboard";
    } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to continue."); } finally { setSubmitting(false); }
  };
  return <main className="auth-page"><section className="auth-intro"><span>🌱</span><h1>WeatherGPT</h1><p>Clear, practical weather support for your farm.</p></section><section className="auth-card"><p className="eyebrow">Welcome</p><h2>{isRegister ? "Create your farmer account" : "Sign in to your account"}</h2><form onSubmit={submit}>{isRegister && <label>Name<input name="name" required autoComplete="name" /></label>}<label>Email<input name="email" required type="email" autoComplete="email" /></label><label>Password<input name="password" required type="password" minLength={8} autoComplete={isRegister ? "new-password" : "current-password"} /></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="primary-button" disabled={submitting}>{submitting ? "Please wait…" : isRegister ? "Create account" : "Sign in"}</button></form><p>{isRegister ? "Already have an account?" : "New to WeatherGPT?"} <a href={isRegister ? "/login" : "/register"}>{isRegister ? "Sign in" : "Create an account"}</a></p></section></main>;
}
