"""Embedding provider contract and deterministic test embedding."""

import hashlib
import math
from collections.abc import Sequence
from typing import Protocol


class EmbeddingProvider(Protocol):
    dimension: int

    def embed(self, text: str) -> Sequence[float]:
        """Return an embedding generated by a configured, trusted model."""


class HashEmbeddingProvider:
    """Deterministic local embedding for tests and development only.

    This is not a semantic model and must not be presented as production retrieval quality.
    """

    def __init__(self, dimension: int = 64) -> None:
        self.dimension = dimension

    def embed(self, text: str) -> tuple[float, ...]:
        values = [0.0] * self.dimension
        for token in text.lower().split():
            index = int(hashlib.sha256(token.encode()).hexdigest(), 16) % self.dimension
            values[index] += 1.0
        norm = math.sqrt(sum(value * value for value in values)) or 1.0
        return tuple(value / norm for value in values)


def cosine_similarity(left: Sequence[float], right: Sequence[float]) -> float:
    if len(left) != len(right):
        raise ValueError("embedding dimensions must match")
    return sum(a * b for a, b in zip(left, right, strict=True))
